### PR TITLE
move provider to main manifest, name dynamically from appid

### PR DESCRIPTION
**Pull request by Bubu**

### CODE REVIEW

**Comment by Bubu** [comment]
Maybe this can also be submitted upstream? Not sure... :thinking:

**Comment by hrj** [comment]
> Maybe this can also be submitted upstream? Not sure..

Yes, that sounds like a good idea. It will avoid merge conflicts in the future, and reduce my maintenance burden.

**Comment by Bubu** [comment]
Submitted upstream: https://github.com/vector-im/riot-android/pull/2580

**Comment by hrj** [comment]
Awesome; thanks!

If you wish, I can tag a release of mini-vector as soon as upstream is merged.

**Pull request closed without merging**
